[General]
include = default.conf
bypass-system = true
dns-server = https://cloudflare-dns.com/dns-query,https://dns.google/dns-query
fallback-dns-server = 1.1.1.1,8.8.8.8,system
always-ip-address = true
hijack-dns = :53
icmp-auto-reply = false
always-real-ip = *
update-url = https://raw.githubusercontent.com/ofen/shadowrocket-config/master/custom.conf

[Rule]
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,tiktokv.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY
GEOIP,RU,DIRECT
