[General]
bypass-system = true
dns-server = quic://dns11.quad9.net,https://1.1.1.1/dns-query,https://dns.google/dns-query
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 169.254.0.0/16, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32
fallback-dns-server = 1.1.1.1,8.8.8.8,system
dns-direct-fallback-proxy = false
hijack-dns = :53
ipv6 = false
prefer-ipv6 = false
dns-direct-system = false
icmp-auto-reply = false
always-reject-url-rewrite = false
private-ip-answer = false
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/ofen/shadowrocket-config/master/custom.conf

[Rule]
# TikTok
DOMAIN-SUFFIX,ibytedtos.com,PROXY
DOMAIN-SUFFIX,tiktokv.com,PROXY
DOMAIN-SUFFIX,tiktokcdn.com,PROXY
DOMAIN-SUFFIX,tiktok.com,PROXY

# Ad
DOMAIN-KEYWORD,adfox,REJECT
DOMAIN-KEYWORD,adriver,REJECT
DOMAIN-KEYWORD,appmetrica,REJECT
DOMAIN-KEYWORD,appsflyersdk,REJECT
DOMAIN-KEYWORD,criteo,REJECT
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,adjust.cn,REJECT
DOMAIN-SUFFIX,adjust.net.in,REJECT
DOMAIN-SUFFIX,adjust.world,REJECT
DOMAIN-SUFFIX,an.yandex.ru,REJECT
DOMAIN-SUFFIX,mc.webvisor.org,REJECT
DOMAIN-SUFFIX,yabs.yandex.ru,REJECT
DOMAIN-SUFFIX,log.strm.yandex.ru,REJECT
DOMAIN-SUFFIX,yadro.ru,REJECT
DOMAIN-SUFFIX,ad.mail.ru,REJECT
DOMAIN-SUFFIX,xray.mail.ru,REJECT
DOMAIN-SUFFIX,portal.mail.ru,REJECT
DOMAIN-SUFFIX,bar.love.mail.ru,REJECT
DOMAIN-SUFFIX,top-fwz1.mail.ru,REJECT
DOMAIN-SUFFIX,st.top100.ru,REJECT
DOMAIN-SUFFIX,tns-counter.ru,REJECT
DOMAIN-SUFFIX,doubleclick.net,REJECT
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,static.cloudflareinsights.com,REJECT
DOMAIN-SUFFIX,static.hotjar.com,REJECT
DOMAIN-SUFFIX,adroll.com,REJECT
DOMAIN-SUFFIX,refersion.com,REJECT
DOMAIN-SUFFIX,mon-va.byteoversea.com,REJECT
DOMAIN-SUFFIX,sgali-mcs.byteoversea.com,REJECT
DOMAIN-SUFFIX,cstatic.weborama.fr,REJECT
DOMAIN-SUFFIX,us04logfiles.zoom.us,REJECT
DOMAIN-SUFFIX,counter.reddigital.ru,REJECT
DOMAIN-SUFFIX,pxaction.com,REJECT
DOMAIN-SUFFIX,dit.whatsapp.net,REJECT
DOMAIN-SUFFIX,metrics.icloud.com,REJECT
DOMAIN-SUFFIX,visor.sberbank.ru,REJECT
DOMAIN-SUFFIX,dsp.upravel.com,REJECT
DOMAIN-SUFFIX,collector.github.com,REJECT
DOMAIN-SUFFIX,amplitude.com,REJECT
DOMAIN-SUFFIX,intelliscapesolutions.com,REJECT
DOMAIN-SUFFIX,ingest.sentry.io,REJECT
DOMAIN-SUFFIX,tracking.intl.miui.com,REJECT
DOMAIN-SUFFIX,tracking.rus.miui.com,REJECT
DOMAIN-SUFFIX,demdex.net,REJECT
DOMAIN-SUFFIX,browser-intake-datadoghq.com,REJECT
DOMAIN-SUFFIX,iadsdk.apple.com,REJECT
DOMAIN-SUFFIX,stocks-analytics-events.apple.com,REJECT
DOMAIN-SUFFIX,push4site.com,REJECT
DOMAIN-SUFFIX,clarity.ms,REJECT
DOMAIN-SUFFIX,fsdifhj.com,REJECT
DOMAIN-SUFFIX,slackb.com,REJECT
DOMAIN-SUFFIX,app-analytics-services.com,REJECT
DOMAIN-SUFFIX,liftoff.io,REJECT
DOMAIN-SUFFIX,vungle.com,REJECT
DOMAIN-SUFFIX,2mdn.net,REJECT
DOMAIN-SUFFIX,adnxs.com,REJECT
DOMAIN-SUFFIX,mgid.com,REJECT
DOMAIN-SUFFIX,taboola.com,REJECT
DOMAIN-SUFFIX,outbrain.com,REJECT
DOMAIN-SUFFIX,fullstory.com,REJECT
DOMAIN-SUFFIX,logrocket.com,REJECT
DOMAIN-SUFFIX,mixpanel.com,REJECT
DOMAIN-SUFFIX,segment.io,REJECT
DOMAIN-SUFFIX,naarakstudio.com,REJECT
DOMAIN-SUFFIX,crashlytics.com,REJECT

# Apple download/static content
DOMAIN-SUFFIX,mzstatic.com,DIRECT
DOMAIN-SUFFIX,cdn-apple.com,DIRECT
DOMAIN-SUFFIX,aaplimg.com,DIRECT

# Other
DOMAIN-SUFFIX,ru,DIRECT
GEOIP,RU,DIRECT

# Final
FINAL,PROXY

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302
